### ISSUE TITLE
Class constructor h cannot be invoked without 'new'

### ISSUE THREAD

**Issue by 7aklhz** [huandzh/superset-ui-plugins-echarts-basic#14]
**Describe the bug**
After installing the plugin, pages do not run and I see in console "Class constructor h cannot be invoked without 'new'". 

It makes reference to the following line:
![Capture d’écran 2020-03-22 à 23 06 27](https://user-images.githubusercontent.com/4387078/77261840-d94d4900-6c91-11ea-8208-3056d6816b65.png)

Please advise

Thank you.

**Comment by huandzh** [comment]
hi, i am glad to help.

Docs as https://github.com/huandzh/superset-ui-plugins-echarts-basic/tree/master/packages/superset-ui-preset-chart-echarts-basic#superset-tips may be helpful

Please let me know if it solves the issue.

**Comment by 7aklhz** [comment]
Hi,

Unfortunately not. I followed your installation guide and got this error. Looking on internet it seems to be a problem related to babel. I not familiar with typescript nor babel. Can you please explain/fix this issue ?

**Comment by huandzh** [comment]
I don't have enough information to reproduce the issue. There may be some wrong with the environment.

As far as i know, this plugin can be integrated and dockerized with superset 0.34.1
