### ISSUE TITLE
Tutorial on how to create another echart

### ISSUE THREAD

**Issue by 7aklhz** [huandzh/superset-ui-plugins-echarts-basic#15]
Hi, 

I am using echarts for a webproject and I would like to reproduce my charts in superset. So I very interested in your plugin. However, could you please make a step by step guide how I can adapt your plugin to other charts ? Could you maybe give a guide / example with scatter [https://echarts.apache.org/examples/en/editor.html?c=bubble-gradient](url) ? 

It would be really great if you could help me :)

Thank you.

**Comment by huandzh** [comment]
hi, a new sub-plugin (something like  `EchartsBubbleGradientPlugin`) is what we need to support the chart.

Please reference the following steps to create the sub-plugin:

1. create a new module just like `Radar` at `superset-ui-plugins-echarts-basic/packages/superset-ui-preset-chart-echarts-basic/src/` (one can copy Radar srcs, rename folder and classes, and then modify the codes to adapt new chart)
1. write a proper `transformProps.ts` which will handle data and generate desired `echarts option`
1. write a plugin class `EchartsBubbleGradientPlugin` which includes customized `controlPanel`, `metadata` and `transformProps`(created in the previous step), and leave `loadChart` as it is to reuse `EchartsBase` (see `Radar.ts` and https://github.com/huandzh/superset-ui-plugins-echarts-basic#tips-on-developing-new-plugin)
1. update thumbnail.png
1. update exports: `index.ts` in the new module, `index.ts` and `preset.ts` at preset root(namely `superset-ui-plugins-echarts-basic/packages/superset-ui-preset-chart-echarts-basic/src/`)

[Contributing guidelines required by superset-ui](https://github.com/apache-superset/superset-ui/blob/master/CONTRIBUTING.md) should be also followed. Storybooks and unit tests are really handy to ensure everything works as expected:

1. add story to `https://github.com/huandzh/superset-ui-plugins-echarts-basic/tree/master/packages/superset-ui-plugins-demo`
1. add unit tests to `superset-ui-plugins-echarts-basic/packages/superset-ui-preset-chart-echarts-basic/test`

I hope these tips are sufficient.

And, you are also very welcome to send pull request to this repo and share your work on supporting bubble gradient! ^_^
